### PR TITLE
Added link to list of supported languages

### PR DESCRIPTION
**Pull request by pardel**
# Description

* Added link to the FB page containing list of supported languages

### CODE REVIEW

**Comment by lornajane** [comment]
I know this was only a copy change but in general, I would prefer us to use the pull request template and increment the version numbers on the edited specs regardless. No need to go back and do anything with this one but in general - the pull request template is there for a reason on this repo.

**Comment by tbedford** [comment]
I always remember to fill out the template on my own PRs and I always seem to forget when reviewing other peoples because when I come to do the review the template is already gone! Is there something we can do to stop that happening besides providing me with a new brain?

**Comment by lornajane** [comment]
Not sure. I think the real problem is that we do have PR templates in other places and we ignore them there! I am also reluctant to automate this because there are lots of valid reasons for not needing exactly that template, for example if making a change to the wider repo and not the spec. I saw it in the email notification but didn't comment until I could see the diff and of course you beat me to the review :)

**Comment by tbedford** [comment]
OK thanks I will try and remember to catch this in future.

**Pull request merged**
