### PR TITLE
Placeholder PR for updates to Messages API

### PR DESCRIPTION
**Pull request by lornajane**
# Description

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

^ No, this description really needs editing before we're ready to merge!

### CODE REVIEW

**Comment by lornajane** [comment]
@slorello89 Is this PR still useful? It's been open for a while!

**Comment by lornajane** [comment]
Not sure if we need this, closing.

**Comment by slorello89** [comment]
@lornajane - going to reopen this - we're going to start looking it now.

**Comment by slorello89** [comment]
Made some updates to this in #407 (the rebase proved to difficult to managed 😭 ) closing this PR again.

**Pull request closed without merging**
