### PR TITLE
Updated Campaign params descriptions

### PR DESCRIPTION
**Pull request by EDDYMENS**
# Description
Updated Campaign params descriptions. 

# Changed
- Improved Campaign parameter descriptions.

# Removed
 - Removed deprecated campaign parameter `affiliate_marketing`.
 
# Checklist
- [x] version number incremented (in the `info` section of the spec)

### CODE REVIEW

**Review by niati — APPROVED** [review]

**Comment by niati** [comment]
Will wait for @pardel 's review before we merge.

**Review by pardel — APPROVED** [review]

**Comment by pardel** [comment]
@EDDYMENS  I've updated the version to resolve conflicts - please make sure you pull the latest changes from the remote branch before adding new changes.

**Comment by pardel** [comment]
NB: the version updates happened during my "recovery" process - the OAS weren't built due to some conflicts.

**Comment by pardel** [comment]
@EDDYMENS could we be a bit more specific on the changes to the specs? These changes will show on our changelogs.

**Comment by EDDYMENS** [comment]
> @EDDYMENS could we be a bit more specific on the changes to the specs? These changes will show on our changelogs.

PR description updated :)

**Review by niati — APPROVED** [review]

**Pull request merged**
