### PR TITLE
Add total_items to get rooms request

### PR DESCRIPTION
**Pull request by elishaikatz**
# Description

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

### CODE REVIEW

**Comment by pardel** [comment]
@elishaikatz would it be possible to have a cursor-based pagination rather than page-based? See https://nexmo.github.io/api-standards/standard/pagination/ for our standars.

**Comment by elishaikatz** [comment]
> @elishaikatz would it be possible to have a cursor-based pagination rather than page-based? See https://nexmo.github.io/api-standards/standard/pagination/ for our standars.

It's doable, but it's a big breaking change now, why do you ask? we created the current pagination based on the page-based from the Nexmo standards

**Comment by pardel** [comment]
@elishaikatz our standards read: "APIs shall use a cursor as their pagination option unless otherwise agreed with DevRel."
https://nexmo.github.io/api-standards/standard/pagination/

**Comment by elishaikatz** [comment]
> @elishaikatz our standards read: "APIs shall use a cursor as their pagination option unless otherwise agreed with DevRel." https://nexmo.github.io/api-standards/standard/pagination/

@pardel  As I know it, this feature was implemented a long time ago, and we are only adding now the total items property - unfortunately, Alex from my team, that implemented this feature, is no longer working at Vonage, so I cannot ask who he worked with a while ago with dev rel, but this was approved - as Meetings API basic proposal was approved.

**Review by pardel — APPROVED** [review]

**Pull request merged**
