### PR TITLE
VNI-184 :: [Custom Workflow] Update OpenSpec API

### PR DESCRIPTION
**Pull request by Dbasdeo**
# Description

What does this pull request achieve? Why do we need it?

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

### CODE REVIEW

**Comment by lornajane** [comment]
Are these fields available to all users? It was my understanding that only certain customers with particular pricing plans would have access - can you clarify?

**Comment by Dbasdeo** [comment]
The pin_code parameter is not available to all users however the workflow_id is. To let people know that pin_code is not available to everyone, in my description, I added: "You must contact 
            [support@nexmo.com](mailto:support@nexmo.com) to enable this 
            feature." 
I copied this line from another parameter that is also not available to all users.

**Comment by lornajane** [comment]
Thanks for clarifying! I am starting by creating the workflow docs since we need to be able to link to these and they will be part of our public documentation. Additional docs for "secret" features can follow but I think all not-generally-available fields should be removed from the spec since users aren't able to tell for themselves what pricing model they have and this could cause confusion.

**Comment by lornajane** [comment]
This PR is superseded by #131 which includes only the features available to all users (we're creating custom docs for the extra features) and also rebases onto the recent changes to this spec.

**Pull request closed without merging**
