### PR TITLE
Make visible each PUT request example from the VAPI spec

### PR DESCRIPTION
**Pull request by bencgreenberg**
# New

* Makes visible the schema for request example types already present in the spec

# Checklist

- [x] version number incremented (in the `info` section of the spec)

### CODE REVIEW

**Comment by mheap** [comment]
```
  141:9    error  oas3-schema              Property `requests` is not expected to be here.
```

What problem is this PR trying to solve?

**Comment by bencgreenberg** [comment]
> ```
>   141:9    error  oas3-schema              Property `requests` is not expected to be here.
> ```
> 
> What problem is this PR trying to solve?

Can you explain to me why adding `requests:` allows the various request examples to be displayed? @yallen011 asked if it was possible, and experimenting locally, I noticed adding that, enabled it. Why is that so? And what's the proper way to do so?

**Comment by bencgreenberg** [comment]
@mheap has indicated the current behavior is actually a bug, and we're going to circle back on this tomorrow during working hours again. Noting it here for reference.

**Comment by lornajane** [comment]
Redoc does show the examples so I think the spec is correct, and we may need to look at the tool to enable this for our own docs.

**Comment by mheap** [comment]
The fix for the renderer is at https://github.com/Nexmo/nexmo-oas-renderer/pull/83

It was a race condition when trying to load within Station

**Pull request closed without merging**
