### PR TITLE
OAS for the VBC APIs

### PR DESCRIPTION
**Pull request by marklewin**
These are a work in progress but it would be good to get them merged so that I can get feedback from the VBC integration project stakeholders and continue working on the VBC docs in NDP.

### CODE REVIEW

**Comment by mheap** [comment]
Looks like the build is failing - the errors are pretty good. Let me know if you'd like a hand resolving any https://travis-ci.com/Nexmo/api-specification/builds/100603124

**Comment by marklewin** [comment]
Thanks @mheap  - wasn't aware of the speccy test and the Swagger online editor didn't pick this up!

**Comment by mheap** [comment]
@marklewin These are an excellent first pass. A couple of opportunities for using `ref` (e.g. `account_id` in extension parameters) and it'd be good to use 

```
components:
  responses:
```

rather than components:schemas (see the `responses` key in https://swagger.io/specification/#componentsObject) as it provides additional validation. `schemas` is the loosest component definition.

As you can work on NDP without this merged, would you like them merging or would you like to keep them on a branch?

**Comment by marklewin** [comment]
Thanks for the feedback Michael. Let's keep this PR open for the time being until I've got the API refs into a more "polished" state?

**Comment by marklewin** [comment]
This needs to be merged along with the following NDP PR: https://github.com/Nexmo/nexmo-developer/pull/1516

**Pull request merged**
